name: C/C++ CI

on:
  push:
    branches: [ flatcar-master ]
  pull_request:
    branches: [ flatcar-master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: |
        sudo apt install -y libblkid-dev libext2fs-dev libmount-dev curl unzip libdbus-glib-1-dev protobuf-compiler libbz2-dev libgflags-dev libssl-dev libgoogle-glog-dev libcurl4-openssl-dev libxml2-dev libprotobuf-dev cmake wget
    - name: prep rootdev
      run: |
        curl -sSL -o /tmp/seismograph.zip https://github.com/kinvolk/seismograph/archive/flatcar-master.zip
        cd /tmp && unzip /tmp/seismograph.zip && cd seismograph-flatcar-master && sh autogen.sh && ./configure && make && sudo make install && sudo ldconfig
    - name: prep googletest
      ## because ubuntu libgtest-dev does not provide the libraries to link against...
      run: |
        curl -sSL -o /tmp/googletest.zip https://github.com/google/googletest/archive/master.zip
        cd /tmp && unzip /tmp/googletest.zip && cd googletest-master && mkdir build && cd build && cmake .. && make && sudo make install
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make -j$(nproc)
    - name: make check
      run: make check -j$(nproc)
      #- name: make distcheck
      #run: make distcheck
